# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app
# Install all dependencies (including dev) so tsx is available
COPY package*.json tsconfig.json ./
RUN npm ci
# Copy source files (including server and code)
COPY src ./src
# Expose no port for stdio
# Start the server using tsx
CMD ["npx", "tsx", "src/server.ts"]
